title: Jay Harnesha
logo: /assets/images/profile-pic-small.jpg
description: Experienced DevOps Engineer skilled in optimizing CI/CD pipelines, automating cloud infrastructure, and fortifying software security. Proficient in Docker, Kubernetes, Prometheus, Terraform, AWS, and Azure. Strong understanding of DevOps Approach and CI/CD methodologies, with a proven ability to streamline workflows through cross-functional collaboration.
#show_downloads: true
theme: jekyll-theme-minimal
